---
- name: Install target host with rtp-engine
  become: true
  become_user: root
  hosts: all
  debugger: false


  tasks:
  - name: Install a list of packages
    ansible.builtin.apt:
      pkg:
      - git
      - python3
      - python3-dev
      - python3-pip
      - net-tools
      autoclean: true
      install_recommends: true
      update_cache: true
      force: true
