---
- name: Install target host with rtp-engine
  become: true
  become_user: root
  # hosts: all
  hosts:
  #  - 172.203.140.149
    - 74.235.212.41
  # roles:
  #   - ansible-role-docker
  # vars:
  #   docker_edition: 'ce'
  #   docker_packages:
  #   - "docker-{{ docker_edition }}"
  #   - "docker-{{ docker_edition }}-cli"
  #   - "docker-{{ docker_edition }}-rootless-extras"
  #   docker_install_compose_plugin: true
  #   docker_compose_package: docker-compose-plugin
  #   docker_compose_package_state: present
  #   docker_packages_state: present

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - wget
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - git
          - python3
          - python3-dev
          - python3-pip
          - net-tools
          - libssl-dev
        autoclean: true
        install_recommends: true
        update_cache: true
        force: true

    - name: Check if cmake is installed with correct version
      ansible.builtin.shell:
        cmd: cmake --version | awk '{print $3}' | head -n 1
      register: cmake_installed
      ignore_errors: true
      # failed_when: int(cmake_installed.stdout) != 3.29.1

    - name: Remove old cmake packages {{ cmake_installed.stdout }}
      ansible.builtin.apt:
        pkg:
          - cmake
        state: absent
        autoclean: true
        force: true
      ignore_errors: true
      when: cmake_installed.stdout != "3.29.1"

    - name: Install cmake from source
      become: true
      block:
        - name: Download cmake from source
          ansible.builtin.shell:
            cmd: |
              wget https://github.com/Kitware/CMake/releases/download/v3.29.1/cmake-3.29.1.tar.gz
          args:
            chdir: /usr/local/src/
          become: true
        - name: Unzip source was downloaded
          ansible.builtin.shell:
            cmd: |
              tar -zxvf cmake-3.29.1.tar.gz
          args:
            chdir: /usr/local/src/
          become: true
        - name: Build source was upzipped
          ansible.builtin.shell:
            cmd: |
              ./configure
              gmake
              make install
          args:
            chdir: /usr/local/src/cmake-3.29.1
          become: true
      when: cmake_installed.stdout != "3.29.1"

    - name: Check if Docker is installed
      ansible.builtin.command:
        cmd: docker -v
      register: docker_installed
      ignore_errors: true
      become: true

    - name: Install Docker
      become: true
      block:
        - name: Add Docker's official GPG key
          block:
            # - name: Update apt
            #   include_tasks: apt.yml
            - name: Install necessary packages
              become: true
              ansible.builtin.apt:
                name:
                  - ca-certificates
                  - curl
                  - gnupg
                state: latest
                update_cache: true
            - name: Add GPG key
              ansible.builtin.shell:
                cmd: |
                  sudo install -m 0755 -d /etc/apt/keyrings
                  curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
                  sudo chmod a+r /etc/apt/keyrings/docker.gpg
        - name: Add the repository to Apt sources
          block:
            - name: Add repos
              ansible.builtin.shell:
                cmd: |
                  echo \
                  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
                  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
                  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            # - name: Update apt
            #   include_tasks: apt.yml

        - name: Install Docker packages
          become: true
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest
            update_cache: true
      when: docker_installed.failed

    - name: Ensure Docker group exists
      become: true
      ansible.builtin.group:
        name: docker
        state: present
      register: docker_group

    - name: Add User to docker group
      become: true
      ansible.builtin.user:
        name: azureuser
        groups: docker
        append: true
      when: docker_group is changed
