- name: Patch servers
  hosts: all
  gather_facts: true

  tasks:

    - name: Perform patch for linux servers
      ansible.builtin.include_role:
        name: rhel
        tasks_from: patch.yml
      when: ansible_os_family == "rhel"
